name: Update Map

on:
  workflow_dispatch:
  schedule:
  # Run this every 8 hours
    - cron: '0 */8 * * *'

jobs:
  create-map:
    name: Create Map
    runs-on: ubuntu-latest
    env:
      ATLAS_URI: ${{ secrets.ATLAS_URI }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm install
      - run: npm start

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update map'
          add: 'map.png'
          push: 'origin main'
